./run js/cheeseTrackers.js
./run js/connections.js
./run js/main.js
./run js/map/customLayout.js
./run js/map/dataLoading.js
./run js/map/interaction.js
./run js/map/launchUrlEditor.js
./run js/map/layout.js
./run js/map/main.js
./run js/map/mapEngine.js
./run js/map/persistence.js
./run js/map/reachability.js
./run js/map/render.js
./run js/map/ruleEngine.js
./run js/map/slotSync.js
./run js/map/state.js
./run js/progFilesUI.js
./run js/progKeys.js
./run js/requirementGroups.js
./run js/slotsUI.js
